# generated by datamodel-codegen:
#   filename:  cit-protocol.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class CapabilityIdentifier(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=128,
            min_length=3,
            pattern='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$',
            title='CapabilityIdentifier',
        ),
    ]


class JsonObject(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )


class CitEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal[1]
    messageId: UUID
    type: Annotated[
        str,
        Field(
            max_length=128,
            min_length=3,
            pattern='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$',
        ),
    ]
    runtimeId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    deviceId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    clientId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    sessionId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    correlationId: Annotated[str | None, Field(max_length=128, min_length=1)] = None
    sequence: Annotated[int | None, Field(ge=0)] = None
    sentAt: AwareDatetime
    expiresAt: AwareDatetime | None = None
    idempotencyKey: Annotated[str | None, Field(max_length=256, min_length=1)] = None
    payload: Any


class SafetyContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    policyId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    armed: bool
    deadmanActive: bool | None = None
    inputConfidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Source(StrEnum):
    student_blocks = 'student_blocks'
    student_python = 'student_python'
    quest = 'quest'
    leap = 'leap'
    instructor = 'instructor'
    agent_mesh = 'agent_mesh'
    system = 'system'


class DeviceCommandIntent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    commandId: UUID
    sessionId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    deviceId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    capability: Annotated[
        str,
        Field(
            max_length=128,
            min_length=3,
            pattern='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$',
            title='CapabilityIdentifier',
        ),
    ]
    action: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[a-z][a-z0-9_]*$',
            title='ActionIdentifier',
        ),
    ]
    arguments: JsonObject
    source: Source
    issuedAt: AwareDatetime
    expiresAt: AwareDatetime
    idempotencyKey: Annotated[str, Field(max_length=256, min_length=1)]
    safetyContext: SafetyContext


class Category(StrEnum):
    connection = 'connection'
    input = 'input'
    telemetry = 'telemetry'
    motion = 'motion'
    sensor = 'sensor'
    safety = 'safety'
    program = 'program'
    diagnostic = 'diagnostic'


class DeviceEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eventId: UUID
    deviceId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    sessionId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    sequence: Annotated[int | None, Field(ge=0)] = None
    category: Category
    name: Annotated[
        str,
        Field(
            max_length=128,
            min_length=3,
            pattern='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$',
        ),
    ]
    values: JsonObject
    sourceTimestamp: AwareDatetime | None = None
    receivedAt: AwareDatetime
    historical: bool = False


class DeviceType(StrEnum):
    robot = 'robot'
    input = 'input'
    xr_client = 'xr_client'
    virtual = 'virtual'
    bridge = 'bridge'


class DeviceDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deviceId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    displayName: Annotated[str, Field(max_length=128, min_length=1)]
    deviceType: DeviceType
    model: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    adapterId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    adapterVersion: Annotated[str, Field(max_length=64, min_length=1)]
    physical: bool
    capabilities: Annotated[
        list[CapabilityIdentifier], Field(max_length=256, min_length=1)
    ]
    safetyProfile: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None


class Status(StrEnum):
    accepted = 'accepted'
    completed = 'completed'
    rejected = 'rejected'
    duplicate = 'duplicate'
    expired = 'expired'
    failed = 'failed'


class CommandResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    commandId: UUID
    deviceId: Annotated[
        str,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ]
    status: Status
    message: Annotated[str | None, Field(max_length=500, min_length=1)] = None
    recordedAt: AwareDatetime
    details: JsonObject | None = None


class Code(StrEnum):
    DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND'
    DEVICE_OFFLINE = 'DEVICE_OFFLINE'
    DEVICE_NOT_ASSIGNED = 'DEVICE_NOT_ASSIGNED'
    DEVICE_LEASE_CONFLICT = 'DEVICE_LEASE_CONFLICT'
    DEVICE_NOT_ARMED = 'DEVICE_NOT_ARMED'
    DEVICE_CAPABILITY_UNSUPPORTED = 'DEVICE_CAPABILITY_UNSUPPORTED'
    COMMAND_EXPIRED = 'COMMAND_EXPIRED'
    COMMAND_DUPLICATE = 'COMMAND_DUPLICATE'
    SAFETY_POLICY_DENIED = 'SAFETY_POLICY_DENIED'
    PROTOCOL_VERSION_UNSUPPORTED = 'PROTOCOL_VERSION_UNSUPPORTED'
    INVALID_MESSAGE = 'INVALID_MESSAGE'


class ProtocolError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    message: Annotated[str, Field(max_length=500, min_length=1)]
    deviceId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    sessionId: Annotated[
        str | None,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9][A-Za-z0-9._-]*$',
            title='Identifier',
        ),
    ] = None
    correlationId: Annotated[str, Field(max_length=128, min_length=1)]
    recoverySuggestion: Annotated[str, Field(max_length=500, min_length=1)]
    details: JsonObject | None = None


class CitProtocolMessage(
    RootModel[
        CitEnvelope
        | DeviceCommandIntent
        | DeviceEvent
        | DeviceDescriptor
        | CommandResult
        | ProtocolError
    ]
):
    root: Annotated[
        CitEnvelope
        | DeviceCommandIntent
        | DeviceEvent
        | DeviceDescriptor
        | CommandResult
        | ProtocolError,
        Field(
            description='Language-neutral foundation messages. This schema does not authorize physical execution.',
            title='CIT Physical XR Protocol V1',
        ),
    ]
