"""LEGO SPIKE and MINDSTORMS support over Pybricks firmware (FR-045 - FR-054)."""

from .adapter import (
    ADAPTER_ID,
    ADAPTER_VERSION,
    HubOwnership,
    HubSafetyLimits,
    PybricksHubAdapter,
    build_adapter,
)
from .autonomous import (
    Display,
    DriveGeometry,
    DriveStraight,
    DriveTurn,
    MotorAngle,
    MotorRun,
    ProgramError,
    Step,
    Wait,
    build_program,
)
from .capabilities import capabilities_for, motor_ports, sensor_port_for
from .diagnostics import HubDiagnostic, HubTransportError
from .discovery import HubBinding, PybricksDiscoveryProvider, TransportFactory
from .fakes import FakeHubTransport
from .hubs import (
    HUB_MODELS,
    ROBOT_INVENTOR,
    SPIKE_ESSENTIAL,
    SPIKE_PRIME,
    HubModel,
    PortKind,
    UnknownHubModel,
    decode_ports,
    encode_ports,
    hub_model,
    parse_port_map,
)
from .protocol import (
    ARITY,
    HOST_OPERATIONS,
    HUB_OPERATIONS,
    MAX_ARGUMENTS,
    MAX_FRAME_CHARS,
    PROTOCOL_TAG,
    PROTOCOL_VERSION,
    Frame,
    FrameError,
    HubErrorCode,
    Operation,
    decode,
    next_sequence,
    sanitize_text,
)
from .transport import HubTransport

__all__ = [
    "ADAPTER_ID",
    "ADAPTER_VERSION",
    "ARITY",
    "HOST_OPERATIONS",
    "HUB_MODELS",
    "HUB_OPERATIONS",
    "MAX_ARGUMENTS",
    "MAX_FRAME_CHARS",
    "PROTOCOL_TAG",
    "PROTOCOL_VERSION",
    "ROBOT_INVENTOR",
    "SPIKE_ESSENTIAL",
    "SPIKE_PRIME",
    "Display",
    "DriveGeometry",
    "DriveStraight",
    "DriveTurn",
    "FakeHubTransport",
    "Frame",
    "FrameError",
    "HubBinding",
    "HubDiagnostic",
    "HubErrorCode",
    "HubModel",
    "HubOwnership",
    "HubSafetyLimits",
    "HubTransport",
    "HubTransportError",
    "MotorAngle",
    "MotorRun",
    "Operation",
    "PortKind",
    "ProgramError",
    "PybricksDiscoveryProvider",
    "PybricksHubAdapter",
    "Step",
    "TransportFactory",
    "UnknownHubModel",
    "Wait",
    "build_adapter",
    "build_program",
    "capabilities_for",
    "decode",
    "decode_ports",
    "encode_ports",
    "hub_model",
    "motor_ports",
    "next_sequence",
    "parse_port_map",
    "sanitize_text",
    "sensor_port_for",
]
