from __future__ import annotations

import asyncio
from collections.abc import Mapping
from datetime import UTC, datetime
from ipaddress import IPv4Address
from pathlib import Path
from urllib.parse import quote

import pytest
from cit_runtime.fabric_auth import FABRIC_PERMISSIONS, FabricBootstrapIdentity
from cit_runtime.fabric_printer import (
    CrealityPrinterService,
    MoonrakerTransport,
    PrinterConfiguration,
    PrinterError,
    PrinterJob,
    PrinterOutcomeUnknownError,
    PrinterProfileConfiguration,
    PrinterState,
    TransportSnapshot,
)
from cit_runtime.fabric_service import create_fabric_app
from fastapi.testclient import TestClient

NOW = datetime(2026, 9, 8, 12, 0, 0, tzinfo=UTC)
ADMIN_TOKEN = "cit-printer-admin-" + "a" * 40
ADMIN_HEADERS = {"Authorization": f"Bearer {ADMIN_TOKEN}"}


class FakeTransport:
    def __init__(self, state: PrinterState = PrinterState.STANDBY) -> None:
        self.state = state
        self.status_calls = 0
        self.uploads: list[tuple[str, str]] = []
        self.starts: list[str] = []
        self.start_error: PrinterError | None = None

    async def status(self) -> TransportSnapshot:
        self.status_calls += 1
        return TransportSnapshot(
            state=self.state,
            checked_at=NOW,
            job=(
                PrinterJob(filename="protected-current-job.gcode", progressPercent=42.0)
                if self.state is PrinterState.PRINTING
                else None
            ),
        )

    async def upload(self, path: Path, *, remote_name: str, checksum: str) -> str:
        assert await asyncio.to_thread(path.is_file)
        self.uploads.append((remote_name, checksum))
        return remote_name

    async def start(self, remote_name: str) -> None:
        self.starts.append(remote_name)
        if self.start_error is not None:
            raise self.start_error


class FakeSlicer:
    def __init__(self) -> None:
        self.calls: list[tuple[Path, str]] = []

    async def slice(
        self,
        source: Path,
        *,
        output_directory: Path,
        profile: PrinterProfileConfiguration,
    ) -> Path:
        self.calls.append((source, profile.profile_id))

        def write_result() -> Path:
            output_directory.mkdir(parents=True)
            result = output_directory / "prepared.gcode"
            result.write_text(
                "; generated by Creality Print test double\n"
                "START_PRINT EXTRUDER_TEMP=220 BED_TEMP=60\n"
                "G28\n",
                encoding="utf-8",
            )
            return result

        return await asyncio.to_thread(write_result)


def profile(tmp_path: Path) -> PrinterProfileConfiguration:
    paths = [tmp_path / name for name in ("printer.json", "process.json", "filament.json")]
    for path in paths:
        path.write_text("{}", encoding="utf-8")
    return PrinterProfileConfiguration(
        profile_id="k1-max-0.4-pla-standard",
        display_name="K1 Max · PLA",
        printer_model="K1 Max",
        nozzle_diameter_mm=0.4,
        filament_name="Generic PLA",
        process_name="0.20 mm Standard",
        printer_settings=paths[0],
        process_settings=paths[1],
        filament_settings=paths[2],
    )


def service(
    tmp_path: Path,
    transport: FakeTransport,
    *,
    locked: bool,
    writes: bool = True,
) -> tuple[CrealityPrinterService, FakeSlicer]:
    slicer = FakeSlicer()
    configured = CrealityPrinterService(
        PrinterConfiguration(
            address=IPv4Address("172.30.1.55"),
            display_name="3D Printer",
            model="Creality K1 Max",
            staging_root=tmp_path / "stage",
            profiles=(profile(tmp_path),),
            moonraker_port=7125,
            network_monitoring_enabled=True,
            remote_writes_enabled=writes,
            current_print_locked=locked,
        ),
        transport=transport,
        slicer=slicer,
        clock=lambda: NOW,
    )
    return configured, slicer


@pytest.mark.asyncio
async def test_locked_snapshot_never_contacts_current_print(tmp_path: Path) -> None:
    transport = FakeTransport(PrinterState.PRINTING)
    printer, _slicer = service(tmp_path, transport, locked=True)

    snapshot = await printer.snapshot(refresh=True)

    assert snapshot.state is PrinterState.CURRENT_PRINT_LOCKED
    assert snapshot.operations.stageSource is True
    assert snapshot.operations.slice is False
    assert snapshot.operations.upload is False
    assert snapshot.operations.start is False
    assert snapshot.operations.lockReasonCode == "current_print"
    assert transport.status_calls == 0


@pytest.mark.asyncio
async def test_model_can_be_staged_locally_but_not_sliced_while_locked(
    tmp_path: Path,
) -> None:
    transport = FakeTransport(PrinterState.PRINTING)
    printer, slicer = service(tmp_path, transport, locked=True)

    source = await printer.stage_source(
        file_name="class-model.stl",
        media_type="model/stl",
        content=b"solid classroom\nendsolid classroom\n",
    )
    snapshot = await printer.snapshot()

    assert snapshot.sources == [source]
    assert transport.status_calls == 0
    with pytest.raises(PrinterError, match="current print is protected"):
        await printer.slice_source(source.artifactId, "k1-max-0.4-pla-standard")
    assert slicer.calls == []


@pytest.mark.asyncio
async def test_upload_and_start_are_separate_one_time_operations(tmp_path: Path) -> None:
    transport = FakeTransport()
    printer, slicer = service(tmp_path, transport, locked=False)
    source = await printer.stage_source(
        file_name="demo.stl",
        media_type="model/stl",
        content=b"solid demo\nendsolid demo\n",
    )

    sliced = await printer.slice_source(source.artifactId, "k1-max-0.4-pla-standard")
    artifact = sliced.snapshot.gcodeArtifacts[0]
    uploaded = await printer.upload_artifact(artifact.artifactId)

    assert len(slicer.calls) == 1
    assert len(transport.uploads) == 1
    assert transport.starts == []
    uploaded_artifact = uploaded.snapshot.gcodeArtifacts[0]
    assert uploaded_artifact.remoteFileName is not None

    intent = await printer.prepare_start(artifact.artifactId, actor_id="instructor-a")
    started = await printer.start_artifact(
        artifact.artifactId,
        actor_id="instructor-a",
        confirmation_token=intent.confirmationToken,
    )

    assert started.snapshot.state is PrinterState.STARTING
    assert transport.starts == [intent.remoteFileName]
    with pytest.raises(PrinterError, match="expired or does not match"):
        await printer.start_artifact(
            artifact.artifactId,
            actor_id="instructor-a",
            confirmation_token=intent.confirmationToken,
        )
    assert transport.starts == [intent.remoteFileName]


@pytest.mark.asyncio
async def test_remote_write_is_rejected_before_upload_when_not_standby(
    tmp_path: Path,
) -> None:
    transport = FakeTransport(PrinterState.PRINTING)
    printer, _slicer = service(tmp_path, transport, locked=False)
    source = await printer.stage_source(
        file_name="demo.3mf",
        media_type="model/3mf",
        content=b"test project",
    )
    sliced = await printer.slice_source(source.artifactId, "k1-max-0.4-pla-standard")
    artifact = sliced.snapshot.gcodeArtifacts[0]

    with pytest.raises(PrinterError, match="no write was sent"):
        await printer.upload_artifact(artifact.artifactId)

    assert transport.uploads == []
    assert transport.starts == []


@pytest.mark.asyncio
async def test_start_transport_failure_is_non_retryable_unknown_outcome(
    tmp_path: Path,
) -> None:
    transport = FakeTransport()
    printer, _slicer = service(tmp_path, transport, locked=False)
    source = await printer.stage_source(
        file_name="demo.stl",
        media_type="model/stl",
        content=b"solid demo\nendsolid demo\n",
    )
    sliced = await printer.slice_source(source.artifactId, "k1-max-0.4-pla-standard")
    artifact = sliced.snapshot.gcodeArtifacts[0]
    await printer.upload_artifact(artifact.artifactId)
    intent = await printer.prepare_start(artifact.artifactId, actor_id="instructor-a")
    transport.start_error = PrinterOutcomeUnknownError(
        "PRINTER_START_OUTCOME_UNKNOWN",
        "unknown",
        status_code=502,
    )

    with pytest.raises(PrinterOutcomeUnknownError):
        await printer.start_artifact(
            artifact.artifactId,
            actor_id="instructor-a",
            confirmation_token=intent.confirmationToken,
        )
    with pytest.raises(PrinterError, match="expired or does not match"):
        await printer.start_artifact(
            artifact.artifactId,
            actor_id="instructor-a",
            confirmation_token=intent.confirmationToken,
        )

    assert len(transport.starts) == 1


@pytest.mark.asyncio
async def test_moonraker_upload_forces_print_false(tmp_path: Path) -> None:
    requests: list[tuple[str, str, bytes | None]] = []

    async def request(
        method: str,
        url: str,
        _headers: Mapping[str, str],
        body: bytes | None,
        _request_timeout: float,
    ) -> tuple[int, bytes]:
        requests.append((method, url, body))
        return (
            201,
            b'{"result":{"item":{"path":"cit-test.gcode"},"print_started":false}}',
        )

    path = tmp_path / "test.gcode"
    path.write_bytes(b"; generated by Creality Print\nSTART_PRINT\n")
    transport = MoonrakerTransport(
        IPv4Address("192.0.2.10"),
        7125,
        request=request,
    )

    await transport.upload(path, remote_name="cit-test.gcode", checksum="a" * 64)

    assert requests[0][0] == "POST"
    assert requests[0][1] == "http://192.0.2.10:7125/server/files/upload"
    payload = requests[0][2]
    assert payload is not None
    assert b'name="print"' in payload
    assert b"\r\n\r\nfalse\r\n" in payload
    assert b"\r\n\r\ntrue\r\n" not in payload


def test_printer_api_stays_locked_and_audits_local_staging(tmp_path: Path) -> None:
    transport = FakeTransport(PrinterState.PRINTING)
    printer, _slicer = service(tmp_path, transport, locked=True)
    identity = FabricBootstrapIdentity(
        identity_id="admin-printer",
        token=ADMIN_TOKEN,
        actor_type="administrator",
        roles=("administrator",),
        permissions=tuple(sorted(FABRIC_PERMISSIONS)),
    )

    with TestClient(
        create_fabric_app(
            database_path=tmp_path / "fabric.sqlite3",
            clock=lambda: NOW,
            fabric_bootstrap_identities=(identity,),
            printer_service=printer,
            maintenance_interval=None,
        )
    ) as client:
        status = client.get("/api/v1/fabric/printer", headers=ADMIN_HEADERS)
        staged = client.post(
            "/api/v1/fabric/printer/sources",
            headers={
                **ADMIN_HEADERS,
                "Content-Type": "model/stl",
                "X-CIT-Filename": quote("교실 모형.stl"),
            },
            content=b"solid lesson\nendsolid lesson\n",
        )
        assert staged.status_code == 200, staged.text
        denied_slice = client.post(
            f"/api/v1/fabric/printer/sources/{staged.json()['artifactId']}/slice",
            headers=ADMIN_HEADERS,
            json={"profileId": "k1-max-0.4-pla-standard"},
        )
        audit = client.get("/api/v1/fabric/audit?limit=50", headers=ADMIN_HEADERS)

    assert status.status_code == 200
    assert status.json()["state"] == "current_print_locked"
    assert staged.status_code == 200
    assert staged.json()["fileName"] == "교실 모형.stl"
    assert denied_slice.status_code == 409
    assert denied_slice.json()["code"] == "PRINTER_CURRENT_PRINT_LOCKED"
    assert transport.status_calls == 0
    actions = [record["action"] for record in audit.json()]
    assert "fabric.printer.source.stage" in actions
    assert "fabric.printer.slice" in actions
