/**
 * Inline the student SDK's Python into a TypeScript module the worker bundles.
 *
 * The worker writes these files into Pyodide's virtual filesystem, so the
 * browser gets the same `citxr` package the Python tests import. Generating it
 * from the real source -- rather than keeping a browser copy -- means the two
 * cannot drift: `pnpm generate:check` fails in CI the moment they do.
 */

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { format } from "prettier";

const root = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const sourceDir = path.join(root, "packages", "student-sdk-py", "src", "citxr");
const targetPath = path.join(
  root,
  "apps",
  "studio-web",
  "src",
  "citxr-sources.ts",
);

const names = (await readdir(sourceDir))
  .filter((name) => name.endsWith(".py"))
  .sort();

const entries = [];
for (const name of names) {
  const text = await readFile(path.join(sourceDir, name), "utf8");
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(text)},`);
}

const generated = await format(
  `// Generated by tools/sdk-codegen/inline-citxr.mjs. Do not edit.
//
// The student SDK's Python, inlined so the Pyodide worker can write it into its
// virtual filesystem. Regenerate with \`pnpm generate\`.

export const CITXR_SOURCES: Readonly<Record<string, string>> = {
${entries.join("\n")}
};
`,
  { parser: "typescript" },
);

if (process.argv.includes("--check")) {
  const committed = await readFile(targetPath, "utf8").catch(() => undefined);
  if (committed !== generated) {
    throw new Error(
      `Inlined student SDK is stale or missing: ${path.relative(root, targetPath)}. Run pnpm generate.`,
    );
  }
  process.stdout.write(
    `Inlined student SDK matches ${names.length} source files.\n`,
  );
} else {
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, generated, "utf8");
  process.stdout.write(`Inlined ${names.length} student SDK source files.\n`);
}
