"""FR-048: autonomous programs are built from steps, never from student text."""

from __future__ import annotations

import pytest
from cit_lego_pybricks import (
    ROBOT_INVENTOR,
    SPIKE_ESSENTIAL,
    SPIKE_PRIME,
    Display,
    DriveStraight,
    DriveTurn,
    MotorAngle,
    MotorRun,
    PortKind,
    ProgramError,
    Step,
    Wait,
    build_program,
)

DRIVING_BASE = {
    "A": PortKind.MOTOR,
    "B": PortKind.MOTOR,
    "C": PortKind.DISTANCE,
    "D": PortKind.EMPTY,
    "E": PortKind.EMPTY,
    "F": PortKind.EMPTY,
}

EXPECTED = """\
# Generated by CIT Physical XR for a LEGO SPIKE Prime Hub.
# Autonomous mode (FR-048): this program runs on the hub with no computer
# attached. Motor power is capped at 75 percent, and the
# program stops every motor even when a step fails.
from pybricks.hubs import PrimeHub
from pybricks.parameters import Port
from pybricks.pupdevices import Motor
from pybricks.robotics import DriveBase
from pybricks.tools import wait

hub = PrimeHub()
motor_a = Motor(Port.A)
motor_b = Motor(Port.B)
drive_base = DriveBase(motor_a, motor_b, wheel_diameter=56, axle_track=114)


def main():
    drive_base.straight(200)
    drive_base.turn(90)
    motor_a.run_time(300, 1000)
    motor_a.run_angle(300, 90)
    wait(500)
    hub.display.text("go")


try:
    main()
finally:
    drive_base.stop()
    motor_a.stop()
    motor_b.stop()
"""


def test_a_program_is_deterministic_and_stops_what_it_started() -> None:
    steps: list[Step] = [
        DriveStraight(millimetres=200, speed=0.3),
        DriveTurn(angle=90, speed=0.3),
        MotorRun(port="A", speed=0.3, seconds=1.0),
        MotorAngle(port="A", angle=90, speed=0.3),
        Wait(seconds=0.5),
        Display(text="go"),
    ]

    program = build_program(SPIKE_PRIME, DRIVING_BASE, steps)

    assert program == EXPECTED
    assert build_program(SPIKE_PRIME, DRIVING_BASE, steps) == program


def test_the_class_power_ceiling_reaches_the_downloaded_program() -> None:
    program = build_program(
        SPIKE_PRIME,
        DRIVING_BASE,
        [MotorRun(port="A", speed=1.0, seconds=10)],
        max_motor_percent=40,
        max_command_milliseconds=1500,
    )

    assert "motor_a.run_time(400, 1500)" in program
    assert "capped at 40 percent" in program


def test_a_program_never_contains_a_way_to_evaluate_text() -> None:
    program = build_program(ROBOT_INVENTOR, DRIVING_BASE, [MotorRun("A", 0.2, 1.0)])

    for forbidden in ("eval(", "exec(", "__import__", "compile("):
        assert forbidden not in program


def test_display_text_is_escaped_and_bounded() -> None:
    program = build_program(SPIKE_PRIME, DRIVING_BASE, [Display(text='say "hi"\nnow' + "x" * 60)])

    assert 'hub.display.text("say \\"hi\\" now' in program
    assert "\n" not in program.split("hub.display.text(")[1].split(")")[0]


def test_a_two_port_hub_cannot_be_told_to_drive_with_one_motor() -> None:
    ports = {"A": PortKind.MOTOR, "B": PortKind.DISTANCE}

    with pytest.raises(ProgramError, match="needs two motors"):
        build_program(SPIKE_ESSENTIAL, ports, [DriveStraight(millimetres=100, speed=0.3)])


def test_a_step_naming_an_empty_port_is_refused() -> None:
    with pytest.raises(ProgramError, match="no motor"):
        build_program(SPIKE_PRIME, DRIVING_BASE, [MotorRun(port="D", speed=0.2, seconds=1)])


def test_a_step_naming_a_port_the_hub_lacks_is_refused() -> None:
    with pytest.raises(ProgramError, match="has no port"):
        build_program(
            SPIKE_ESSENTIAL,
            {"A": PortKind.MOTOR, "B": PortKind.MOTOR},
            [MotorRun(port="F", speed=0.2, seconds=1)],
        )


def test_an_empty_program_is_refused_rather_than_installed() -> None:
    with pytest.raises(ProgramError, match="at least one step"):
        build_program(SPIKE_PRIME, DRIVING_BASE, [])
